# Generated by Django 5.1 on 2024-08-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calummara', '0002_venda_preco_venda_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nome_produto',
        ),
    ]
