# Generated by Django 5.1 on 2024-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calummara', '0003_rename_nome_produto_nome_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendas_mes', models.IntegerField()),
                ('quant_itens', models.IntegerField()),
                ('valor_venda', models.IntegerField()),
            ],
        ),
    ]
